name: Docker Build and Push

on: 
  workflow_dispatch:  # Manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Set in your repo secrets
        password: ${{ secrets.DOCKER_PASSWORD }}  # Set in your repo secrets

    - name: Build Docker image
      run: |
        docker build -t skullpion91/tictactoe:latest .
        
    - name: Push Docker image
      run: |
        docker push skullpion91/tictactoe:latest
